-- Enable Row Level Security
alter table if exists public.history enable row level security;

-- Create history table if not exists
create table if not exists public.history (
    id bigint generated by default as identity primary key,
    video_url text not null,
    video_title text,
    comment text,
    thumbnail_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create function to create history table
create or replace function public.create_history_table()
returns void
language plpgsql
security definer
as $$
begin
    -- Create the table if it doesn't exist
    create table if not exists public.history (
        id bigint generated by default as identity primary key,
        video_url text not null,
        video_title text,
        comment text,
        thumbnail_url text,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
    );
    
    -- Enable RLS
    alter table if exists public.history enable row level security;
end;
$$;
